FROM python:3.12-slim

# -u equivalent: don't buffer logs, don't litter .pyc files
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /

COPY backend/ .

# Installing dependencies
COPY backend/requirements.txt /app/requirements.txt

# ENTRYPOINT ["tail", "-f", "/dev/null"]

RUN pip install --no-cache-dir -v -r /app/requirements.txt

# Create app user trigger
RUN useradd -m appuser
USER appuser

EXPOSE 8000

# ENTRYPOINT ["tail", "-f", "/dev/null"]

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]