# ========== BUILD ==========

# Use a minimal Node.js image
FROM node:18-slim AS build

# Set working directory
WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

# ENTRYPOINT ["tail", "-f", "/dev/null"]

RUN npm ci

COPY frontend/ .

ARG VITE_BACKEND_URL
ARG VITE_BACKEND_PATH
ARG VITE_PROJECT_NAME
ARG VITE_PROJECT_VERSION

ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_BACKEND_PATH=$VITE_BACKEND_PATH
ENV VITE_PROJECT_NAME=$VITE_PROJECT_NAME
ENV VITE_PROJECT_VERSION=$VITE_PROJECT_VERSION

RUN npm run build

# ========== RUN =========

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY docker/frontend/nginx.staging.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# ENTRYPOINT ["tail", "-f", "/dev/null"]

CMD ["nginx", "-g", "daemon off;"]
